### ISSUE TITLE
celeba download error

### ISSUE THREAD

**Issue by AntonVeynshter** [makeyourownneuralnetwork/gan#1]
Hello,
first of all thank you very much for your books. I hope to see more and as soon as passible :).

I have a problem with downloading of celeba dataset.  I will just continue on my own hardware, but wanted to share the issue

`BadZipFile                                Traceback (most recent call last)

<ipython-input-21-06ac0dc73e63> in <module>()
      1 
----> 2 mnist_dataset = torchvision.datasets.CelebA(root='.', download=True)

3 frames

/usr/lib/python3.6/zipfile.py in _RealGetContents(self)
   1196             raise BadZipFile("File is not a zip file")
   1197         if not endrec:
-> 1198             raise BadZipFile("File is not a zip file")
   1199         if self.debug > 1:
   1200             print(endrec)

BadZipFile: File is not a zip file`

**Comment by makeyourownneuralnetwork** [comment]
hi @Leo16112 - is this still an issue?

sometimes the google colab environment can be temperamental and restarting an environment can fix these issues

let me know if this is still a problem for you

**Comment by AntonVeynshter** [comment]
Hello @makeyourownneuralnetwork ,

I was looking for a solution and found out, that it happens sometimes, because it could be out of download limits. But it was two weeks ago, so I did not keep the link.
I solved it by downloading the data set from the original source.

Thank you very much for your respond.
