### ISSUE TITLE
Second code cell in 10_celeba_download_make_hdf5.ipynb zip file error

### ISSUE THREAD

**Issue by wwoofbum** [makeyourownneuralnetwork/gan#2]
Running this notebook in Google Colab results in the following error:

BadZipFile                                Traceback (most recent call last)
<ipython-input-6-07ee85e0a7fa> in <module>()
      1 # download data
      2 
----> 3 mnist_dataset = torchvision.datasets.CelebA(root='.', download=True)

3 frames
/usr/lib/python3.6/zipfile.py in _RealGetContents(self)
   1196             raise BadZipFile("File is not a zip file")
   1197         if not endrec:
-> 1198             raise BadZipFile("File is not a zip file")
   1199         if self.debug > 1:
   1200             print(endrec)

BadZipFile: File is not a zip file

**Comment by wwoofbum** [comment]
Error repeated 3 times.  Closed application, went away for 6 hours, re-opened application, tried again, cell completed successfully, notebook completed successfully.

**Comment by makeyourownneuralnetwork** [comment]
I'm glad this was fixed. I have seen several reports that the download process to google cola can fail, or a reset of the virtual machine can lose the downloaded data

**Comment by tiansiyuan** [comment]
I got similar error message when try to download the data:

BadZipFile                                Traceback (most recent call last)
<ipython-input-11-07ee85e0a7fa> in <module>()
      1 # download data
      2 
----> 3 mnist_dataset = torchvision.datasets.CelebA(root='.', download=True)

3 frames
/usr/local/lib/python3.7/dist-packages/torchvision/datasets/celeba.py in __init__(self, root, split, target_type, transform, target_transform, download)
     78 
     79         if download:
---> 80             self.download()
     81 
     82         if not self._check_integrity():

/usr/local/lib/python3.7/dist-packages/torchvision/datasets/celeba.py in download(self)
    152             download_file_from_google_drive(file_id, os.path.join(self.root, self.base_folder), filename, md5)
    153 
--> 154         with zipfile.ZipFile(os.path.join(self.root, self.base_folder, "img_align_celeba.zip"), "r") as f:
    155             f.extractall(os.path.join(self.root, self.base_folder))
    156 

/usr/lib/python3.7/zipfile.py in __init__(self, file, mode, compression, allowZip64, compresslevel)
   1256         try:
   1257             if mode == 'r':
-> 1258                 self._RealGetContents()
   1259             elif mode in ('w', 'x'):
   1260                 # set the modified flag so central directory gets written

/usr/lib/python3.7/zipfile.py in _RealGetContents(self)
   1323             raise BadZipFile("File is not a zip file")
   1324         if not endrec:
-> 1325             raise BadZipFile("File is not a zip file")
   1326         if self.debug > 1:
   1327             print(endrec)

BadZipFile: File is not a zip file

**Comment by tiansiyuan** [comment]
I've seen the following:

RuntimeError: The daily quota of the file img_align_celeba.zip is exceeded and it can't be downloaded. This is a limitation of Google Drive and can only be overcome by trying again later.

Before and after waiting for over night, I saw above "not a zip file" message.
